### ISSUE TITLE
Checking promise is missing from 02.extra-2.js

### ISSUE THREAD

**Issue by chumanfu** [kentcdodds/advanced-react-hooks#106]
Hi,
I have just completed the training for the second extra credit for part 2 and I noticed that final version is missing the following from the run function:

`    if (!promise) {
      return
    }`

Is this correct?
This would make the run function look like this:

`
  const run = React.useCallback(promise => {
    if (!promise) {
      return
    }
    dispatch({type: 'pending'})
    promise.then(
      data => {
        dispatch({type: 'resolved', data})
      },
      error => {
        dispatch({type: 'rejected', error})
      },
    )`

Thanks

**Comment by kentcdodds** [comment]
Hi @chumanfu,

The nice part of the change we've made is that now instead of expecting people to call `run` with `undefined`, we just expect them to *not* call `run` **at all** if they don't want to trigger state changes. So that's what we do:

```javascript
  React.useEffect(() => {
    if (!pokemonName) {
      return
    }
    run(fetchPokemon(pokemonName))
  }, [pokemonName, run])
```

We only call `run` if we have a `pokemonName` to fetch.

I hope that makes sense :)

**Comment by chumanfu** [comment]
Thanks for your reply. I still don't see how 02.extra02.js means that we don't need to check the promise since in 02.js we checked both pokemon and the promise.
Could there still not be a situation where fetchPokemon could not return a valid promise?

**Comment by kentcdodds** [comment]
If you dive into the implementation of `fetchPokemon`, you'll see that it *always* returns a promise. If `run` were typed with TypeScript, it would require that the value it receives is a Promise and then you'd get static type checking that you're always passing a promise.
