### ISSUE TITLE
Promise resolving question

### ISSUE THREAD

**Issue by jgarciallamas** [kentcdodds/advanced-react-hooks#114]
Hi Kent,

I hope you are doing well despite the situation.

 Regarding the exercise, ./src/exercise/03.extra-2.js, **caching in a context provider**, I just wanted to ask you about this chunk of code:

**In the 03.extra-2.js file**

![image](https://user-images.githubusercontent.com/22444788/104377382-b80e5f80-5526-11eb-9f48-cee7e4184357.png)

**In the utils.js file**

![image](https://user-images.githubusercontent.com/22444788/104377606-10456180-5527-11eb-849e-0b25320567cf.png)

When the data information about one particular pokemon is not in the cache, then the run function is called. As far as I can understand, and this is my doubt, it seems as if we are resolving the same promise twice, I think in order to sync the async call of the API and then store the information in cache. Are we technically resolving the promise twice? If this is the case, could we have any kind of issue by doing that?

1.
![image](https://user-images.githubusercontent.com/22444788/104377486-e12ef000-5526-11eb-803e-a85509d7b6da.png)

2.
![image](https://user-images.githubusercontent.com/22444788/104377543-f572ed00-5526-11eb-83d4-8b37bcba9f98.png)

Thank you very much in advance Kent for any kind of comment.
Jose

**Comment by kentcdodds** [comment]
Hi @jgarciallamas, remember that simply attaching `.then` onto a promise does not "resolve" the promise. It's simply a way to say: "when this promise is resolved, do this." So you can do:

```javascript
const promise = Promise.resolve()

promise.then(() => {})
promise.then(() => {})
promise.then(() => {})
promise.then(() => {})
promise.then(() => {})
```

And that promise is only resolved once. Also, you can only ever resolve a promise once.

I hope that helps clear things up. If you have further questions, you're welcome to join me during [office hours](https://kcd.im/office-hours) 👍  Good luck!
