### ISSUE TITLE
Start the TypeScript-fication process by creating a `ts/main` branch

### ISSUE THREAD

**Issue by suddenlyGiovanni** [kentcdodds/advanced-react-hooks#116]
Hi @kentcdodds, could you create a `ts/main` branch from HEAD `main` as you did for the other workshop ex (https://github.com/kentcdodds/react-fundamentals/tree/ts/main), so that we could contribute to the typescript examples?

**Comment by kentcdodds** [comment]
Done!

Thanks for the contributions! I'm not sure how everything's going to look for the workshops by the way. I'm pretty sure I want the whole workshop to be accomplishable even if folks know nothing about TypeScript and don't specify any types. So instructions shouldn't default to using types (though they can be added in addition to the primary examples which have no types).

I don't think I'll have any instructions for adding types in the comments of the exercises either. But the final version can definitely have the types.

Still playing around with all of this. And I really appreciate you taking time to make pull requests for things! Even if I don't merge those directly, they're a great reference if I get stuck 😅

**Comment by suddenlyGiovanni** [comment]
I agree. 
I best the best course of action, in my opinion, would be to embrace the progressive enchantment approach; 
- convert the base setup to leverage typescript (dependencies, tsconfig, .etc)
- maintain the exercises in JS (but also enabling them to switch to TS with zero friction)
- maintain the final IN JS
- provide the same finals also in Typescript.

The rationale behind it is that even developers writing JavaScript would be helped by the typescript implementation to better understand React's API, but not forced to switch to a different branch to see them. 

To avoid confusion, the documentation for the typescript implementation could live within the typescript finals.

**Comment by kentcdodds** [comment]
I think I'm ok with this solution. If you don't mind, I'd prefer to work on this myself until I have a good feel for how I want it all to work.

You can feel free to continue making PRs if you like, but it's more likely I'd use those as references as needed than actually merge them. I appreciate your willingness to help and I hope it's been an instructional experience for you as well! Thanks for all your help!

**Comment by kentcdodds** [comment]
@all-contributors please add @suddenlyGiovanni for ideas

**Comment by kentcdodds** [comment]
FYI, I've decided to go with a different approach. I'm going to maintain a `next` branch which will be the next version of the workshops. That's where I'll make all changes that I want to for the workshop (including new exercises/TypeScript/etc.). Then, when I re-record all the videos, `next` will become `main` and the old `main` will get a special branch for historical reasons.

I think this'll be a lot easier to manage for everyone. If someone wants to try the TypeScript stuff, they can use the `next` branch. They'll just have to accept that some of the code will be different from the videos until I get around to updating the videos.
