### ISSUE TITLE
Tests doesn't pass for `extra-1` in exercise 6

### ISSUE THREAD

**Issue by lemieszek** [kentcdodds/advanced-react-hooks#133]
## Case:

change import from ` '../final/06'` to ` '../final/06.extra-1'`

```github
++import App from '../final/06.extra-1'
--import App from '../final/06'
```

## Error:
```
🚨 Make sure to call `useDebugValue` with the formatted value
```

## Info

I was confused, as I did extra credit and tests wasn't passing.

When I checked @kentcdodds implementation, it wasn't different much from mine.

I checked the test against ` '../final/06.extra-1'` and it failed.

**Tests should** pass. as `useDebugValue` is working correctly, as you can see here:

![image](https://user-images.githubusercontent.com/37555757/114105374-ea80ec00-98cc-11eb-8993-c54d8e5c0357.png)

**Comment by kentcdodds** [comment]
Thanks for the suggestion. I've added a test for this extra credit :)
