### ISSUE TITLE
useContext gotchas

### ISSUE THREAD

**Issue by bouzlibop** [kentcdodds/advanced-react-hooks#166]
Hi, I believe it would be helpful to note somewhere [this context caveat](https://reactjs.org/docs/context.html#caveats).

For example in `advanced-react-hooks/src/final/03.js`:

```js
function CountProvider(props) {
  const [count, setCount] = React.useState(0)
  const value = [count, setCount]
  // could also do it like this:
  // const value = React.useState(0)
  return <CountContext.Provider value={value} {...props} />
}
```

The code will re-render all consumers every time the Provider re-renders because a new object is always created for `value`.

**Comment by kentcdodds** [comment]
Yep, that's for the performance workshop 😁 stay tuned!
