### ISSUE TITLE
React DevTools only works on isolated page

### ISSUE THREAD

**Issue by alicnik** [kentcdodds/advanced-react-hooks#167]
Because the main exercise view renders the exercise in an iframe, React DevTools doesn't include those contents. This is a known limitation: https://github.com/facebook/react/issues/18945. It's a small issue in this context but slightly confusing, especially on exercise 6, `useDebugValue: useMedia` which explicitly requires the use of the DevTools.

There's a simple-enough fix where you place the following in the `<head>` of `public/index.html`:
```html
<script type="text/javascript">
  if (window.parent) {
    window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__
  }
</script>
```

I couldn't find a good reason for not including this and, for me at least, it solved a problem which distracted me from the learning experience. Would it be worth updating the repos with this fix? 

If there is a good reason for not including this, then perhaps some clarification in the instructions would help people like me foolishly doing this in the morning without enough coffee.

**Comment by alicnik** [comment]
Undeniably true, it is a noisy shell. Thanks for your thoughts, and thanks for Epic React!

**Comment by kentcdodds** [comment]
Thanks! :)
