### ISSUE TITLE
useLayoutEffect: auto-scrolling textarea

### ISSUE THREAD

**Issue by zapalagrzegorz** [kentcdodds/advanced-react-hooks#184]
It doesn't seem to be working. Final version is slaggy.
Copied final version into sandbox also disabled Infinite Loop Protection:
https://codesandbox.io/s/optimistic-wave-rm42xw

**Comment by kentcdodds** [comment]
As noted in the workshop instructions:

> NOTE: React 18 has smoothed out the differences in the UX between useEffect and useLayoutEffect. That said, the simple "rule" described still applies!
