### ISSUE TITLE
useDebugValue - production deploys don't show anything

### ISSUE THREAD

**Issue by kenneth-gray** [kentcdodds/advanced-react-hooks#190]
I suspect `useDebugValue` is a noop in production deployments. Therefore the devtools don't show any labels for minified hook names.

Potential options:
1. Remove links to production deployments for this exercise
2. Build development versions for production deployments

You could mention it in the text instead, but I'm not sure that's a good option.

**Comment by kentcdodds** [comment]
I think it's useful for people to see that it doesn't do anything in production so we'll keep the links, but adding a note in the instructions sounds helpful. Would you like to do that?

**Comment by kenneth-gray** [comment]
Sure 👍
