### ISSUE TITLE
React Developer Tools hooks weird rendering

### ISSUE THREAD

**Issue by jposadas** [kentcdodds/advanced-react-hooks#28]
Hi, was going through these amazing examples and noticed an issue with the React Developer Tools when working on `exercise/06.js`.

**Steps to reproduce:**
1. `npm run start`
2. Navigate to http://localhost:3000/6
3. Open the React Developer Tools and inspect the `Box` component

You'll see that subsequent hooks calls are nested (even though that's not what the code is doing). If you click on the `Copy to Clipboard` button, you'll see the same in the JSON.
![Screen Shot 2020-04-11 at 6 26 49 PM](https://user-images.githubusercontent.com/3272590/79041398-27ff5a80-7c22-11ea-8425-30c12e2dd8b8.png)

* I added a `React.useState('red')` call to see if this behavior was unique to multiple calls to the same hook, but the nesting seems to happen on all hooks.

However, if we run the exercise code isolated (http://localhost:3000/isolated/exercise/06.js), the hooks appear correctly.
![Screen Shot 2020-04-11 at 6 30 28 PM](https://user-images.githubusercontent.com/3272590/79041452-a0feb200-7c22-11ea-9814-aa0485be8234.png)

Perhaps this issue should go to the React team, but since it only happens in one scenario, maybe there's something in the wrapper code that's triggering it.

Cheers!

**Comment by kentcdodds** [comment]
That's odd. It *might* have to do with the fact that we're using https://github.com/kentcdodds/stop-runaway-react-effects

If you want to do some more digging and potentially report it to the react team that would be great. Either way, I don't think I'll be doing anything about it in this repository. Thanks anyway!
