### ISSUE TITLE
Pokemon API is Down

### ISSUE THREAD

**Issue by fonstack** [kentcdodds/advanced-react-hooks#46]
The same thing that happened with react-hooks workshop. In section two the pokemon API is used

**Comment by kentcdodds** [comment]
Yep, I fixed it in the react-hooks workshop yesterday. I'll fix this one tomorrow. Thanks! 😁

**Comment by kentcdodds** [comment]
Fixed :) Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @fonstack for bugs
