### ISSUE TITLE
I would like to contribute to this repo

### ISSUE THREAD

**Issue by gugol2** [kentcdodds/advanced-react-hooks#49]
Hi @kentcdodds,

I saw a little improvement for this repo and I would like to contribute if possible.

How can I push my branch so that I can open a PR?
I tried to follow the steps here: https://github.com/kentcdodds/advanced-react-hooks/blob/main/CONTRIBUTING.md
But I got this error:
`unable to access 'https://github.com/kentcdodds/advanced-react-hooks.git/': The requested URL returned error: 403`

My contribution is simple, just to use the step prop in the extra-4 of exercise 1, so that the extra-4 case is more compatible with the previous cases:

01.md
```javascript
const [state, dispatch] = React.useReducer(countReducer, {
  count: initialCount,
})
const {count} = state
const increment = () => dispatch({type: 'INCREMENT', step})
```

src/final/01.extra-4.js
```
function countReducer(state, action) {
  const {type, step} = action
  switch (type) {
    case 'increment': {
      return {count: state.count + step}
    }
    default: {
      throw new Error(`Unsupported action type: ${action.type}`)
    }
  }
}

function Counter({initialCount = 0, step = 1}) {
  const [state, dispatch] = React.useReducer(countReducer, {
    count: initialCount,
  })
  const {count} = state
  const increment = () => dispatch({type: 'increment', step})
  return <button onClick={increment}>{count}</button>
}
```

Could you please give me a hand to push my code to this repo?

**Comment by kentcdodds** [comment]
Hi @gugol2! I'd love to have you as a contributor.

Give this short free video course a watch. It should help: http://makeapullrequest.com

**Comment by gugol2** [comment]
I did so before, but skipping some bits here and there and I precisely skipped the fork step...  :sweat_smile:

Thanks for your help @kentcdodds!
