### ISSUE TITLE
Markdown ref-style links aren't rendered on website

### ISSUE THREAD

**Issue by b2m9** [kentcdodds/advanced-react-hooks#66]
Not sure where to report it but there's a tiny problem with reference-style links on the epicreact.dev website.

They just render as normal text instead of links like `[git][git] v2 or greater` for all workshops; all `README.md` have a couple of those at the beginning. The source seems to be the respective workshop repos but I assume the actual website repo isn't public. So can't fix it but I hope it helps somehow. 

Example: https://epicreact.dev/modules/advanced-react-hooks/advanced-react-hooks-welcome

**Comment by kentcdodds** [comment]
Thanks @b2m9! We'll get that fixed.

**Comment by kentcdodds** [comment]
A fix is deploying now :)
