### ISSUE TITLE
useLayoutEffect: auto-growing textarea should have a different name

### ISSUE THREAD

**Issue by l3szcz** [kentcdodds/advanced-react-hooks#79]
In Exercise 4 the exercise name doesn't correspond the exercise content. The exercise should have a name like "auto scrolling chat". Currently there is no "growing" action and technically no "textarea" (as it's used in HTML).

Growing textarea would be something like what's enabled by this package: [https://github.com/buildo/react-autosize-textarea](https://github.com/buildo/react-autosize-textarea).

**Comment by diegorodriguesvieira** [comment]
I agree with @l3szcz

**Comment by kentcdodds** [comment]
Yeah, you're write, this is incorrectly named. I'll get that fixed.

**Comment by kentcdodds** [comment]
Thanks!
