### ISSUE TITLE
useDebugValue: before and after images are not displayed

### ISSUE THREAD

**Issue by vasilii-kovalev** [kentcdodds/advanced-react-hooks#81]
After image:
![image](https://user-images.githubusercontent.com/10310491/96582412-eabc0980-12e3-11eb-8293-046190e41749.png)

Before image:
![image](https://user-images.githubusercontent.com/10310491/96582369-db3cc080-12e3-11eb-994b-8657015436de.png)

`*.js` files are displayed
![image](https://user-images.githubusercontent.com/10310491/96582480-058e7e00-12e4-11eb-9b3d-02d3bd35d7a8.png)

as well as `*.md` ones
![image](https://user-images.githubusercontent.com/10310491/96582509-0fb07c80-12e4-11eb-889d-38eea9c7764f.png)

but `*.png` can't be.
![image](https://user-images.githubusercontent.com/10310491/96581505-949a9680-12e2-11eb-94fa-bc5799c3e5b5.png)

The files exist in `build` folder.
OS: Windows 10

**Comment by kentcdodds** [comment]
Thanks for letting me know! I'm pushing a fix now. I'll get it updated asap.

@all-contributors please add @vasilii-kovalev for bugs
